# Generated by Django 5.1.6 on 2025-06-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades_history', '0017_trades_if_you_could_only_make_10_trades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='All_Trendlines_Up',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Days_In_Pattern_Before_Entry',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='EPS_breakout',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Earnings_Last_Q_20_Pct',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Earnings_Quality',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Earnings_Surprises',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Expanding_Margins',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Fundamentals_Quality',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Over_10_pct_Avg_Surprise',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Ownership_Pct_Change_Past_Earnings',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Positive_Analysts_EPS_Revisions',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Positive_Analysts_Price_Revisions',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Quarters_With_75pct_Surprise',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Spikes_On_Volume',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Started_Off_Correction',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Strong_Quarterly_Sales',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Strong_Yearly_Sales',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Sudden_Growth_Change',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='Volume_Confirmation',
        ),
    ]
