import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 113 stocks total (original 63 + 50 new ones)
tickers = yf.Tickers('''
    MSFT AAPL GOOG AMZN META NVDA TSLA V JPM JNJ PG WMT KO 
    AMD INTC CSCO ORCL CRM IBM QCOM ADBE NFLX DIS 
    BAC GS MS AXP C BLK MA SCHW USB WFC 
    CVX XOM BP RDS-A COP EOG SLB OXY MPC PSX 
    UNH CVS MRK PFE ABT BMY LLY AMGN GILD MDT 
    HD LOW TGT COST NKE SBUX MCD YUM BABA ABNB 
    CAT BA GE HON MMM UPS FDX RTX LMT DE 
    VZ T TMUS ATVI EA ZM SQ PYPL
    SPOT U SNOW PLTR DDOG NET CRWD PATH ZS FTNT
    AMT CCI DLR EQIX PLD WELL VTR ARE MPW BXP
    F GM TM HMC RACE LCID RIVN FSR NIO XPEV
    CCL RCL MAR HLT H IHG WH CHH VAC ABNB
    PM MO BTI JAZZ TAP STZ BF-B DEO MNST KDP
    EL CLX KMB CHD PEP K GIS CPB HSY KHC'''.split())

# Create a list of all ticker symbols for downloading
all_tickers = '''
    MSFT AAPL GOOG AMZN META NVDA TSLA V JPM JNJ PG WMT KO 
    AMD INTC CSCO ORCL CRM IBM QCOM ADBE NFLX DIS 
    BAC GS MS AXP C BLK MA SCHW USB WFC 
    CVX XOM BP RDS-A COP EOG SLB OXY MPC PSX 
    UNH CVS MRK PFE ABT BMY LLY AMGN GILD MDT 
    HD LOW TGT COST NKE SBUX MCD YUM BABA ABNB 
    CAT BA GE HON MMM UPS FDX RTX LMT DE 
    VZ T TMUS ATVI EA ZM SQ PYPL
    SPOT U SNOW PLTR DDOG NET CRWD PATH ZS FTNT
    AMT CCI DLR EQIX PLD WELL VTR ARE MPW BXP
    F GM TM HMC RACE LCID RIVN FSR NIO XPEV
    CCL RCL MAR HLT H IHG WH CHH VAC ABNB
    PM MO BTI JAZZ TAP STZ BF-B DEO MNST KDP
    EL CLX KMB CHD PEP K GIS CPB HSY KHC'''.split()

tickers.tickers['MSFT'].quarterly_income_stmt
yf.download(all_tickers, period='1mo')

print(tickers.tickers['MSFT'].quarterly_income_stmt)