from django.db import models

class Trades(models.Model):
    ID = models.IntegerField(primary_key=True)
    Ticker = models.CharField(max_length=10)
    Status = models.CharField(max_length=50)
    Entry_Date = models.DateField()
    Exit_Date = models.DateField(null=True, blank=True)
    Entry_Price = models.FloatField()
    Exit_Price = models.FloatField(null=True, blank=True)
    Pattern = models.CharField(max_length=100)
    Days_In_Pattern_Before_Entry = models.IntegerField()
    Price_Tightness_1_Week_Before = models.FloatField()
    Exit_Reason = models.CharField(max_length=200)
    Market_Condition = models.CharField(max_length=100)
    Category = models.CharField(max_length=100)
    Earnings_Quality = models.IntegerField()
    Fundamentals_Quality = models.IntegerField()
    Has_Earnings_Acceleration = models.BooleanField()
    Has_Catalyst = models.BooleanField()
    Earnings_Last_Q_20_Pct = models.BooleanField()
    IPO_Last_10_Years = models.BooleanField()
    Nr_Bases = models.IntegerField()
    Volume_Confirmation = models.BooleanField()
    Is_BioTech = models.BooleanField()
    Earnings_Surprises = models.BooleanField()
    Expanding_Margins = models.BooleanField()
    EPS_breakout = models.BooleanField()
    Strong_annual_EPS = models.BooleanField()
    Signs_Acceleration_Will_Continue = models.BooleanField()
    Sudden_Growth_Change = models.BooleanField()
    Strong_Quarterly_And_Yearly_Sales = models.BooleanField()
    Positive_Analysts_Revisions = models.BooleanField()
    Ownership_Pct_Change_Past_Earnings = models.BooleanField()
    Quarters_With_75pct_Surprise = models.BooleanField()
    Over_10_pct_Avg_Surprise = models.BooleanField()

    def __str__(self):
        return f"{self.Ticker} - {self.Entry_Date}"